name: Backend CI

# 1. When should this run?
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 2. What should it do?
jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Grab the code from the repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest httpx

    - name: Run Pytest Suite
      env:
        DATABASE_URL : sqlite:///./test_ci_database.db
        SECRET_KEY : This=is-test-environment-keys-blah-blah
        EXPIRATION_TIME_MINUTES : 30
        EXPIRATION_TIME_DAYS : 3
        ALGORITHM : HS256
        SENDER_EMAIL : your_email@gmail.com
        SENDER_PASSWORD : your_16_character_app_password
        ADMIN_EMAIL : admin_receiving_email@gmail.com
      run: |
        pytest -v